[PLT-4933] Add ability to retain timestamp after aggregation
Quarticai/QuarticSDK pull request #115
Opened 2021-07-29 11:46 UTC by shubham-quartic

Updated the docstrings here and added the constants. We will allow three operations for now, either to discard the timestamp information after aggregation (the behaviour it was now) or to keep the first or last in the group.

Send extra key in `transformations` when type is `aggregation`, called `aggregation_timestamp` to describe the desired behaviour for above.

The default behaviour is to keep the last timestamp, and this field isn't required.

2021-08-05 07:05 UTC, shivinquartic requested changes
PLT-4933 ? Where is the QPD ticket?

2021-08-05 07:29 UTC, shubham-quartic commented
> PLT-4933 ? Where is the QPD ticket?

This is an older ticket
cc. @mprasoonquartic

2021-08-05 10:13 UTC, scriperdjq submitted a review, later dismissed

2021-08-09 05:59 UTC, shivinquartic approved these changes

2021-08-09 05:59 UTC, shivinquartic commented
I hope this being tracked in some QPD ticket.

2021-08-09 06:18 UTC, scriperdjq approved these changes

2021-08-09 07:05 UTC, merged