Qpd 388 build
Quarticai/QuarticSDK pull request #119
Opened 2021-08-06 07:57 UTC by manoj016

2021-08-06 08:51 UTC, shivinquartic approved these changes
lgtm

2021-08-09 02:10 UTC, shubham-quartic commented
Wouldn't this have conflict with tensorflow from same repository?
```tensorflow 2.5.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.```

2021-08-09 02:11 UTC, shubham-quartic requested changes

2021-08-09 02:11 UTC, shubham-quartic commented on requirements.txt
> -six==1.15.0
Wouldn't this have conflict with tensorflow from same repository?
```tensorflow 2.5.0 requires six~=1.15.0, but you have six 1.16.0 which is incompatible.```

2021-08-09 02:13 UTC, shubham-quartic commented on requirements.txt
> -six==1.15.0
Also numpy, why is that bumped?
```  - tensorflow==2.5.0 [requires: numpy~=1.19.2]```

2021-08-23 05:20 UTC, manoj016 commented
Closing this as its not required.

2021-08-23 05:20 UTC, closed without merging