QPD-1470: updated documentation as per the new changes
Quarticai/QuarticSDK pull request #185
Opened 2021-11-15 03:43 UTC by niharp2

Updated readthedocs as per the new changes in implementation and use.

2021-11-15 11:55 UTC, jacob-issac requested changes

2021-11-15 11:55 UTC, jacob-issac commented on docs/source/_build/_sources/model_creation.rst.txt
> +predict can return none, in case if there is any missing previous data.
"if there" can be removed

2021-11-15 11:55 UTC, jacob-issac commented on docs/source/_build/_sources/model_creation.rst.txt
> +the model is deployed the previous data will be fetched automatically for the streaming datapoints.
deployed,

2021-11-15 11:55 UTC, jacob-issac commented on docs/source/_build/model_creation.html
> +predict can return none, in case if there is any missing previous data.
looks like an incomplete sentence

2021-11-15 11:55 UTC, jacob-issac commented on docs/source/_build/model_creation.html
> +3. Users are expected to pass data for one datapoint along with its respective previous data in input_df while experimenting, it is when once
"it is when" can be removed

2021-11-15 11:55 UTC, jacob-issac commented on docs/source/_build/model_creation.html
> +the model is deployed the previous data will be fetched automatically for the streaming datapoints.
deployed,

2021-11-15 14:43 UTC, jacob-issac approved these changes

2021-11-16 04:27 UTC, scriperdjq approved these changes

2021-11-16 08:16 UTC, merged