QPD-5982: Added wide_df functionality in fetching data
Quarticai/QuarticSDK pull request #343
Opened 2024-02-15 07:59 UTC by ArjunGajmer1

2024-02-15 15:16 UTC, scriperdjq submitted a review, later dismissed

2024-02-15 15:27 UTC, tushar-quartic approved these changes

2024-02-16 05:47 UTC, tushar-quartic requested changes
Add wide_df example and include it in parameters as well.

2024-02-16 06:52 UTC, tushar-quartic approved these changes

2024-02-16 06:57 UTC, Aasmeen-Khan approved these changes

2024-02-16 07:52 UTC, merged