Add docs
Quarticai/QuarticSDK pull request #45
Opened 2021-02-19 17:55 UTC by mprasoonquartic

Move docs from md to rst

2021-02-20 00:23 UTC, scriperdjq reviewed
why is it raised against master?

2021-02-20 01:09 UTC, mprasoonquartic commented
> why is it raised against master?

We are keeping the `master` branch as the main branch in SDK instead of `develop`. So, we can remove `develop` from usage, based upon discussion with @pr4n

2021-02-20 01:19 UTC, scriperdjq commented
Not sure why we decided that. This means every individual change requires a bump in production package. We are following develop branch strategy for other repo for multiple other reasons that were earlier discussed (https://nvie.com/posts/a-successful-git-branching-model/). None of that is applicable here?

2021-02-21 16:06 UTC, pr4n reviewed
No change in README?

2021-02-21 16:10 UTC, pr4n requested changes
Without the presence of updates README, I am unable to generate documentation locally. Hence I can not proceed.

2021-02-22 08:46 UTC, mprasoonquartic commented
> Without the presence of updates README, I am unable to generate documentation locally. Hence I can not proceed.

Yes. I have updated the README

2021-02-22 14:31 UTC, DineshQuartic submitted a review, later dismissed

2021-02-22 14:33 UTC, vibhuQuartic approved these changes

2021-02-22 14:41 UTC, pr4n submitted a review, later dismissed
Minor changes. LGTM otherwise

2021-02-22 14:41 UTC, pr4n commented on docs/source/index.rst
> +to build custom applications. uartic SDK supports two kinds of authentication: Basic Authentication
Spelling of Quartic

2021-02-22 14:41 UTC, pr4n commented on docs/source/index.rst
> +to build custom applications. uartic SDK supports two kinds of authentication: Basic Authentication
doesnt make sense 
> Using the Quartic SDK, third party developers who
 to build custom applications

2021-02-22 14:41 UTC, pr4n commented on docs/source/model_creation.rst
> +init
`.init` ?

2021-02-22 14:41 UTC, pr4n commented on docs/source/model_creation.rst
> +ModelABC
I had a discusion with @DineshQuartic to update this to QuarticBaseModel. Maybe thats in another PR? Will this need to be updated when that PR Merges?

2021-02-22 14:41 UTC, pr4n commented on docs/source/model_creation.rst
> +init
This is also at other places. APIClient's init.

2021-02-22 15:17 UTC, DineshQuartic commented on docs/source/model_creation.rst
> +ModelABC
I think few of lines were missed in doc update, updating same with mayank

2021-02-22 15:19 UTC, DineshQuartic commented on docs/source/model_creation.rst
> +init
init in here is useful for client when he call `super().__init__(**params)` while implementing `BaseQuarticModel`. I think this should be `__init__` not init

2021-02-22 15:24 UTC, mprasoonquartic commented on docs/source/index.rst
> +to build custom applications. uartic SDK supports two kinds of authentication: Basic Authentication
resolved

2021-02-22 15:24 UTC, mprasoonquartic commented on docs/source/index.rst
> +to build custom applications. uartic SDK supports two kinds of authentication: Basic Authentication
resolved

2021-02-22 15:26 UTC, mprasoonquartic commented on docs/source/model_creation.rst
> +init
removed init from other places

2021-02-22 15:40 UTC, DineshQuartic commented on docs/source/model_creation.rst
> +super().\ **init**\  with above parameters.
I think this note should be above .save, this note is related to init method

2021-02-22 15:46 UTC, pr4n approved these changes
Okay. I am good at the moment. We will anyways update the doc to fetch it from the generated code comments later. So its lgtm

2021-02-22 15:47 UTC, DineshQuartic approved these changes

2021-02-22 15:48 UTC, merged