Completed BDD tests
Quarticai/QuarticSDK pull request #47
Opened 2021-02-20 18:51 UTC by mprasoonquartic

1. More BDD tests
2. More unit tests

2021-02-21 16:18 UTC, pr4n requested changes
As mentioned in README, running the following command throws errors.
```
 aloe quartic_sdk/tests/
E
======================================================================
ERROR: Failure: OSError (No such file /Users/pranav/workspace/QuarticSDK/quartic_sdk/tests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pranav/workspace/QuarticSDK/venv/lib/python3.7/site-packages/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
OSError: No such file /Users/pranav/workspace/QuarticSDK/quartic_sdk/tests

----------------------------------------------------------------------
Ran 1 test in 0.002s

FAILED (errors=1)
```

2021-02-21 17:38 UTC, pr4n requested changes
Not a scope of this PR, but I fail to see typed return types and parameters. This could be another PR later.

2021-02-21 17:38 UTC, pr4n commented on tests/features/tag_data_flow/__init__.py
> +    assert world.first_tag.id == 1
Remove magic number

2021-02-21 17:38 UTC, pr4n commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        self.id = random.randint(1, 100000000)
This might result in a situation where occurrences have same IDs.
- Why is `id` needed when the API does not provide it?

2021-02-21 17:38 UTC, pr4n commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +            if transformation_type == "interpolation":
Should this be a constant somewhere?

2021-02-21 17:38 UTC, pr4n commented on tests/features/asset_data_flow/__init__.py
> +    assert world.client_assets.first().id == 1
no magic numbers

2021-02-21 17:38 UTC, pr4n commented on tests/features/asset_data_flow/__init__.py
> +    assert world.first_asset.id == 1
no magic numbers

2021-02-21 17:38 UTC, pr4n commented on tests/features/asset_data_flow/flow.feature
> +Feature: Computations to fetch asset data from sdk
Fetch Asset Data with and without transformations

2021-02-21 17:38 UTC, pr4n commented on tests/features/tag_data_flow/flow.feature
> +Feature: Computations to fetch tag data from the sdk
Fetch tag data with and without transformations

2021-02-21 17:52 UTC, pr4n reviewed
Pay close attention to Sourcery stats. The file tag_data_iterator has 17% decrease in Quality due to these changes.

2021-02-21 17:52 UTC, pr4n commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +                if not (transformation.get("aggregation_column")
simplify to `if transformation.get("aggregation_column") is None and transformation.get("aggregation_dict") is None`

2021-02-21 17:52 UTC, pr4n commented on quartic_sdk/core/iterators/tag_data_iterator.py
>                  if not transformation.get("column"):
`if transformation.get("column") is None` is more readable.

2021-02-21 19:34 UTC, mprasoonquartic commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        self.id = random.randint(1, 100000000)
It is to ensure that duplicate entity are not added in the entity list when it is created

2021-02-21 19:35 UTC, mprasoonquartic commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +            if transformation_type == "interpolation":
don't think, that is required, since this is being used only here, and the constant name is self-explanatory

2021-02-22 08:48 UTC, pr4n commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        self.id = random.randint(1, 100000000)
Can use `uuid.uuid1().int` to generate a unique ID?https://docs.python.org/3/library/uuid.html#module-uuid

2021-02-22 09:34 UTC, mprasoonquartic commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        self.id = random.randint(1, 100000000)
done

2021-02-22 09:57 UTC, scriperdjq submitted a review, later dismissed

2021-02-22 09:58 UTC, KishanKishore commented on README.md
> +aloe
Will be using this library or ```behave``` ?

2021-02-22 09:58 UTC, KishanKishore commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        super().__init__(body_json, api_helper)
How is this random integer relevant here ? Can the user use this id to query the context frame instance from the database ?

2021-02-22 09:58 UTC, KishanKishore commented on tests/core/test_entity_generic.py
> +def test_entity_equality():
This seems like a unit test case. Are we writing both unit tests and behavioral test cases ?

2021-02-22 09:58 UTC, KishanKishore commented on tests/features/asset_data_flow/__init__.py
> +from unittest import mock
Is it mandatory to write the steps in the ```init``` file ?

2021-02-22 09:58 UTC, KishanKishore commented on tests/features/tag_list_data_flow/__init__.py
> +def step_impl(context):
As part of the next PR we might want to move this step to a utility file as this seems to be repeated.

2021-02-22 10:18 UTC, mprasoonquartic commented on README.md
> +aloe
for sdk, we are using this

2021-02-22 10:19 UTC, mprasoonquartic commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        super().__init__(body_json, api_helper)
nope. present because this needs to be added for entitylist `add` uniqueness

2021-02-22 10:20 UTC, mprasoonquartic commented on tests/core/test_entity_generic.py
> +def test_entity_equality():
yes. since, the unit tests are only to test the specific method functionality while behavior tests test the complete flow

2021-02-22 10:20 UTC, mprasoonquartic commented on tests/features/asset_data_flow/__init__.py
> +from unittest import mock
didn't get you?

2021-02-22 10:20 UTC, mprasoonquartic commented on tests/features/tag_list_data_flow/__init__.py
> +def step_impl(context):
it's a single line. don't think, there is any  advantage of doing this

2021-02-22 10:28 UTC, KishanKishore commented on tests/features/asset_data_flow/__init__.py
> +from unittest import mock
As discussed this will be addressed as part of another PR.

2021-02-22 10:28 UTC, KishanKishore submitted a review, later dismissed
Looks ok. Mostly behavioral test cases and indentation changes.

2021-02-22 11:56 UTC, pr4n commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        self.id = uuid.uuid1(node=self.start["start_time"]).int
Why only start time? Why not stop time also? The uniqueness is from both params

2021-02-22 12:50 UTC, mprasoonquartic commented on quartic_sdk/core/entities/context_frame_occurrence.py
> +        self.id = uuid.uuid1(node=self.start["start_time"]).int
this is removed now

2021-02-22 13:17 UTC, pr4n approved these changes

2021-02-22 13:19 UTC, KishanKishore approved these changes

2021-02-22 13:31 UTC, shivinquartic approved these changes
lgtm

2021-02-22 13:41 UTC, merged