Fix PLT-4724
Quarticai/QuarticSDK pull request #67
Opened 2021-03-09 06:46 UTC by mprasoonquartic

2021-03-10 01:19 UTC, scriperdjq submitted a review, later dismissed

2021-03-10 03:01 UTC, pr4n requested changes
Tests?

2021-03-10 03:01 UTC, pr4n commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +        The method approximates granularity to the nearest possibility
Add this detail as comment for the granularity param in __init__

2021-03-10 03:58 UTC, pr4n requested changes

2021-03-10 03:58 UTC, pr4n commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +        The method approximates granularity to the nearest possibility
On second thought this change should go in API. So that the behaviour is consistent. This change in SDK is not complete. Please close this PR and create another one in the API along with test cases.

2021-03-10 06:34 UTC, scriperdjq commented on quartic_sdk/utilities/constants.py
> +GRANULARITIES = [0,5,30,60,300,1200,3600,10800,21600,43200,86400]
do you still need this?

2021-03-10 06:37 UTC, mprasoonquartic commented on quartic_sdk/utilities/constants.py
> +GRANULARITIES = [0,5,30,60,300,1200,3600,10800,21600,43200,86400]
removed

2021-03-11 03:08 UTC, scriperdjq approved these changes

2021-03-12 04:57 UTC, pr4n approved these changes

2021-03-12 04:59 UTC, merged