PLT-4935
Quarticai/QuarticSDK pull request #85
Opened 2021-04-07 19:30 UTC by mprasoonquartic

Modify to handle pagination based upon cursor instead of offset

2021-04-08 02:57 UTC, pr4n requested changes

2021-04-08 02:57 UTC, pr4n commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +                    raise Exception(
`Exception` is a very high level class. Typically one does subclass it with a more reasonable name like `class InvalidTransformationException(Exception): pass` and then use this Exception. This makes it's catch better and more relevant.

2021-04-08 10:50 UTC, mprasoonquartic commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +                    raise Exception(
done

2021-04-08 19:42 UTC, KishanKishore reviewed
Could add more details to the documentation strings.

2021-04-09 02:51 UTC, mprasoonquartic commented on quartic_sdk/core/entities/asset.py
>      def event_frames(self):
Providing that will leead to circular ddependency error. heence removed all

2021-04-09 02:51 UTC, mprasoonquartic commented on quartic_sdk/core/entities/edge_connector.py
> +    def data(self, start_time, stop_time, granularity=0, return_type=Constants.RETURN_PANDAS, batch_size=Constants.DEFAULT_PAGE_LIMIT_ROWS, transformations=[]):
Providing that will leead to circular ddependency error. heence removed all

2021-04-09 09:42 UTC, scriperdjq submitted a review, later dismissed

2021-04-14 09:20 UTC, KishanKishore reviewed
Minor comments related to documentation strings and return types.

2021-04-14 09:20 UTC, KishanKishore commented on quartic_sdk/core/entities/asset.py
>      def event_frames(self):
Mention it in the documentation string.

2021-04-14 09:20 UTC, KishanKishore commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +        Get the next object in the iteration.
return type is missing documentation string.

2021-04-14 09:20 UTC, KishanKishore commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +    def return_complete_data_frame_from_iterator(tag_data_iterator):
Provide the return type here.

2021-04-16 07:18 UTC, mprasoonquartic commented on quartic_sdk/core/entities/asset.py
>      def event_frames(self):
will be adding the type hints separately when updating the docs

2021-04-16 09:55 UTC, mprasoonquartic commented on quartic_sdk/core/iterators/tag_data_iterator.py
> +    def return_complete_data_frame_from_iterator(tag_data_iterator):
let me handle this seperately while updating the docs

2021-04-16 10:02 UTC, pr4n approved these changes

2021-04-16 10:11 UTC, scriperdjq approved these changes

2021-04-16 10:15 UTC, merged